import { CustomersType } from "../models/customers";

export const customersData: CustomersType[] = [
  {
    id: 1,
    code: "CUST001",
    name: "Budi Santoso",
    image: "/users/user1.jpeg",
    email: "budi.santoso@email.com",
    phone: "0895634689984",
    address: "Jl. Merdeka No. 10, Jakarta Pusat",
  },
  {
    id: 2,
    code: "CUST002",
    name: "Siti Aminah",
    image: "/users/user2.jpeg",
    email: "siti.aminah@email.com",
    phone: "0895634689984",
    address: "Jl. Raya Bogor KM 20, Depok",
  },
  {
    id: 3,
    code: "CUST003",
    name: "Agus Pratama",
    image: "/users/user3.jpeg",
    email: "agus.pratama@email.com",
    phone: "0895634689984",
    address: "Perumahan Griya Asri Blok B2 No.5, Bandung",
  },
  {
    id: 4,
    code: "CUST004",
    name: "Dewi Lestari",
    image: "/users/user4.jpeg",
    email: "dewi.lestari@email.com",
    phone: "0895634689984",
    address: "Jl. Malioboro No. 7, Yogyakarta",
  },
  {
    id: 5,
    code: "CUST005",
    name: "Andi Wijaya",
    image: "/users/user5.jpeg",
    email: "andi.wijaya@email.com",
    phone: "0895634689984",
    address: "Kompleks Taman Melati No. 12, Surabaya",
  },
  {
    id: 6,
    code: "CUST006",
    name: "Rina Marlina",
    image: "/users/user1.jpeg",
    email: "rina.marlina@email.com",
    phone: "081234567890",
    address: "Jl. Sudirman No. 15, Medan",
  },
  {
    id: 7,
    code: "CUST007",
    name: "Fajar Nugroho",
    image: "/users/user2.jpeg",
    email: "fajar.nugroho@email.com",
    phone: "082345678901",
    address: "Jl. Diponegoro No. 22, Semarang",
  },
  {
    id: 8,
    code: "CUST008",
    name: "Lina Sari",
    image: "/users/user3.jpeg",
    email: "lina.sari@email.com",
    phone: "083456789012",
    address: "Jl. Ahmad Yani No. 8, Makassar",
  },
  {
    id: 9,
    code: "CUST009",
    name: "Dedi Kurniawan",
    image: "/users/user4.jpeg",
    email: "dedi.kurniawan@email.com",
    phone: "084567890123",
    address: "Jl. Gajah Mada No. 3, Palembang",
  },
  {
    id: 10,
    code: "CUST010",
    name: "Maya Putri",
    image: "/users/user5.jpeg",
    email: "maya.putri@email.com",
    phone: "085678901234",
    address: "Jl. Sisingamangaraja No. 11, Medan",
  },
  {
    id: 11,
    code: "CUST011",
    name: "Hendra Saputra",
    image: "/users/user1.jpeg",
    email: "hendra.saputra@email.com",
    phone: "086789012345",
    address: "Jl. Pahlawan No. 9, Malang",
  },
  {
    id: 12,
    code: "CUST012",
    name: "Yuni Astuti",
    image: "/users/user2.jpeg",
    email: "yuni.astuti@email.com",
    phone: "087890123456",
    address: "Jl. Gatot Subroto No. 14, Denpasar",
  },
  {
    id: 13,
    code: "CUST013",
    name: "Rizky Ramadhan",
    image: "/users/user3.jpeg",
    email: "rizky.ramadhan@email.com",
    phone: "088901234567",
    address: "Jl. Pemuda No. 6, Balikpapan",
  },
  {
    id: 14,
    code: "CUST014",
    name: "Sari Dewi",
    image: "/users/user4.jpeg",
    email: "sari.dewi@email.com",
    phone: "089012345678",
    address: "Jl. Asia Afrika No. 2, Bandung",
  },
  {
    id: 15,
    code: "CUST015",
    name: "Bambang Setiawan",
    image: "/users/user5.jpeg",
    email: "bambang.setiawan@email.com",
    phone: "081122334455",
    address: "Jl. Veteran No. 18, Surakarta",
  },
  {
    id: 16,
    code: "CUST016",
    name: "Nina Kartika",
    image: "/users/user1.jpeg",
    email: "nina.kartika@email.com",
    phone: "082233445566",
    address: "Jl. Dr. Sutomo No. 20, Pekanbaru",
  },
  {
    id: 17,
    code: "CUST017",
    name: "Dian Prasetyo",
    image: "/users/user2.jpeg",
    email: "dian.prasetyo@email.com",
    phone: "083344556677",
    address: "Jl. Imam Bonjol No. 13, Pontianak",
  },
  {
    id: 18,
    code: "CUST018",
    name: "Wulan Anggraini",
    image: "/users/user3.jpeg",
    email: "wulan.anggraini@email.com",
    phone: "084455667788",
    address: "Jl. Teuku Umar No. 7, Banda Aceh",
  },
  {
    id: 19,
    code: "CUST019",
    name: "Rudi Hartono",
    image: "/users/user4.jpeg",
    email: "rudi.hartono@email.com",
    phone: "085566778899",
    address: "Jl. Letjen S. Parman No. 5, Samarinda",
  },
  {
    id: 20,
    code: "CUST020",
    name: "Mega Sari",
    image: "/users/user5.jpeg",
    email: "mega.sari@email.com",
    phone: "086677889900",
    address: "Jl. Jenderal Sudirman No. 16, Manado",
  },
];
