import { OrdersType } from "../models/orders";

export const ordersData: OrdersType[] = [
  {
    id: 1,
    orderNumber: "0001",
    orderDate: "2024-05-20",
    status: "processing",
    totalAmount: 250000,
    paymentMethod: "Transfer Bank BCA",
    customerName: "Budi Santoso",
    shippingAddress: "Jl. Merdeka No. 10, Jakarta Pusat",
    courier: "JNE",
    trackingNumber: "JNE1234567890",
  },
  {
    id: 2,
    orderNumber: "0002",
    orderDate: "2024-05-21",
    status: "shipped",
    totalAmount: 175000,
    paymentMethod: "COD",
    customerName: "Siti Aminah",
    shippingAddress: "Jl. Raya Bogor KM 20, Depok",
    courier: "SiCepat",
    trackingNumber: "SICEPAT987654321",
  },
  {
    id: 3,
    orderNumber: "0003",
    orderDate: "2024-05-19",
    status: "delivered",
    totalAmount: 320000,
    paymentMethod: "OVO",
    customerName: "Agus Pratama",
    shippingAddress: "Perumahan Griya Asri Blok B2 No.5, Bandung",
    courier: "J&T Express",
    trackingNumber: "JTEXP123456789",
  },
  {
    id: 4,
    orderNumber: "0004",
    orderDate: "2024-05-18",
    status: "cancelled",
    totalAmount: 90000,
    paymentMethod: "Transfer Bank Mandiri",
    customerName: "Dewi Lestari",
    shippingAddress: "Jl. Malioboro No. 7, Yogyakarta",
    courier: "Pos Indonesia",
    trackingNumber: "POSINDO00098765",
  },
  {
    id: 5,
    orderNumber: "0005",
    orderDate: "2024-05-22",
    status: "pending",
    totalAmount: 450000,
    paymentMethod: "GoPay",
    customerName: "Andi Wijaya",
    shippingAddress: "Kompleks Taman Melati No. 12, Surabaya",
    courier: "AnterAja",
    trackingNumber: "ANTERAJA543210",
  },
  {
    id: 6,
    orderNumber: "0006",
    orderDate: "2024-05-23",
    status: "processing",
    totalAmount: 210000,
    paymentMethod: "Transfer Bank BRI",
    customerName: "Rina Sari",
    shippingAddress: "Jl. Sudirman No. 15, Medan",
    courier: "JNE",
    trackingNumber: "JNE2345678901",
  },
  {
    id: 7,
    orderNumber: "0007",
    orderDate: "2024-05-24",
    status: "shipped",
    totalAmount: 180000,
    paymentMethod: "COD",
    customerName: "Fajar Nugroho",
    shippingAddress: "Jl. Diponegoro No. 8, Semarang",
    courier: "SiCepat",
    trackingNumber: "SICEPAT876543210",
  },
  {
    id: 8,
    orderNumber: "0008",
    orderDate: "2024-05-25",
    status: "delivered",
    totalAmount: 275000,
    paymentMethod: "DANA",
    customerName: "Lina Marlina",
    shippingAddress: "Jl. Ahmad Yani No. 22, Makassar",
    courier: "J&T Express",
    trackingNumber: "JTEXP234567890",
  },
  {
    id: 9,
    orderNumber: "0009",
    orderDate: "2024-05-26",
    status: "cancelled",
    totalAmount: 120000,
    paymentMethod: "Transfer Bank BNI",
    customerName: "Yusuf Hidayat",
    shippingAddress: "Jl. Gajah Mada No. 3, Malang",
    courier: "Pos Indonesia",
    trackingNumber: "POSINDO00123456",
  },
  {
    id: 10,
    orderNumber: "0010",
    orderDate: "2024-05-27",
    status: "pending",
    totalAmount: 390000,
    paymentMethod: "ShopeePay",
    customerName: "Sari Dewi",
    shippingAddress: "Jl. Pahlawan No. 9, Solo",
    courier: "AnterAja",
    trackingNumber: "ANTERAJA654321",
  },
  {
    id: 11,
    orderNumber: "0011",
    orderDate: "2024-05-28",
    status: "processing",
    totalAmount: 260000,
    paymentMethod: "Transfer Bank BCA",
    customerName: "Dian Prasetyo",
    shippingAddress: "Jl. Pemuda No. 11, Palembang",
    courier: "JNE",
    trackingNumber: "JNE3456789012",
  },
  {
    id: 12,
    orderNumber: "0012",
    orderDate: "2024-05-29",
    status: "shipped",
    totalAmount: 150000,
    paymentMethod: "COD",
    customerName: "Tina Anggraini",
    shippingAddress: "Jl. Sisingamangaraja No. 5, Pekanbaru",
    courier: "SiCepat",
    trackingNumber: "SICEPAT765432109",
  },
  {
    id: 13,
    orderNumber: "0013",
    orderDate: "2024-05-30",
    status: "delivered",
    totalAmount: 310000,
    paymentMethod: "OVO",
    customerName: "Rudi Hartono",
    shippingAddress: "Jl. Gatot Subroto No. 17, Denpasar",
    courier: "J&T Express",
    trackingNumber: "JTEXP345678901",
  },
  {
    id: 14,
    orderNumber: "0014",
    orderDate: "2024-05-31",
    status: "cancelled",
    totalAmount: 95000,
    paymentMethod: "Transfer Bank Mandiri",
    customerName: "Maya Sari",
    shippingAddress: "Jl. Asia Afrika No. 2, Bandung",
    courier: "Pos Indonesia",
    trackingNumber: "POSINDO00234567",
  },
  {
    id: 15,
    orderNumber: "0015",
    orderDate: "2024-06-01",
    status: "pending",
    totalAmount: 470000,
    paymentMethod: "GoPay",
    customerName: "Bambang Setiawan",
    shippingAddress: "Jl. Dipatiukur No. 14, Bandung",
    courier: "AnterAja",
    trackingNumber: "ANTERAJA765432",
  },
  {
    id: 16,
    orderNumber: "0016",
    orderDate: "2024-06-02",
    status: "processing",
    totalAmount: 230000,
    paymentMethod: "Transfer Bank BRI",
    customerName: "Sinta Dewi",
    shippingAddress: "Jl. Slamet Riyadi No. 6, Surakarta",
    courier: "JNE",
    trackingNumber: "JNE4567890123",
  },
  {
    id: 17,
    orderNumber: "0017",
    orderDate: "2024-06-03",
    status: "shipped",
    totalAmount: 160000,
    paymentMethod: "COD",
    customerName: "Eko Prabowo",
    shippingAddress: "Jl. Dr. Sutomo No. 4, Pontianak",
    courier: "SiCepat",
    trackingNumber: "SICEPAT654321098",
  },
  {
    id: 18,
    orderNumber: "0018",
    orderDate: "2024-06-04",
    status: "delivered",
    totalAmount: 295000,
    paymentMethod: "DANA",
    customerName: "Wulan Sari",
    shippingAddress: "Jl. Teuku Umar No. 13, Bali",
    courier: "J&T Express",
    trackingNumber: "JTEXP456789012",
  },
  {
    id: 19,
    orderNumber: "0019",
    orderDate: "2024-06-05",
    status: "cancelled",
    totalAmount: 110000,
    paymentMethod: "Transfer Bank BNI",
    customerName: "Hendra Gunawan",
    shippingAddress: "Jl. Ahmad Dahlan No. 7, Padang",
    courier: "Pos Indonesia",
    trackingNumber: "POSINDO00345678",
  },
  {
    id: 20,
    orderNumber: "0020",
    orderDate: "2024-06-06",
    status: "pending",
    totalAmount: 410000,
    paymentMethod: "ShopeePay",
    customerName: "Putri Anggraeni",
    shippingAddress: "Jl. Letjen S. Parman No. 18, Jakarta Barat",
    courier: "AnterAja",
    trackingNumber: "ANTERAJA876543",
  },
  {
    id: 21,
    orderNumber: "0021",
    orderDate: "2024-06-07",
    status: "processing",
    totalAmount: 240000,
    paymentMethod: "Transfer Bank BCA",
    customerName: "Galih Saputra",
    shippingAddress: "Jl. Cendrawasih No. 21, Tangerang",
    courier: "JNE",
    trackingNumber: "JNE5678901234",
  },
  {
    id: 22,
    orderNumber: "0022",
    orderDate: "2024-06-08",
    status: "shipped",
    totalAmount: 170000,
    paymentMethod: "COD",
    customerName: "Mega Putri",
    shippingAddress: "Jl. Kenanga No. 3, Bekasi",
    courier: "SiCepat",
    trackingNumber: "SICEPAT543210987",
  },
  {
    id: 23,
    orderNumber: "0023",
    orderDate: "2024-06-09",
    status: "delivered",
    totalAmount: 285000,
    paymentMethod: "OVO",
    customerName: "Rizky Ramadhan",
    shippingAddress: "Jl. Melati No. 8, Bogor",
    courier: "J&T Express",
    trackingNumber: "JTEXP567890123",
  },
  {
    id: 24,
    orderNumber: "0024",
    orderDate: "2024-06-10",
    status: "cancelled",
    totalAmount: 105000,
    paymentMethod: "Transfer Bank Mandiri",
    customerName: "Sulastri",
    shippingAddress: "Jl. Mawar No. 2, Cirebon",
    courier: "Pos Indonesia",
    trackingNumber: "POSINDO00456789",
  },
  {
    id: 25,
    orderNumber: "0025",
    orderDate: "2024-06-11",
    status: "pending",
    totalAmount: 430000,
    paymentMethod: "GoPay",
    customerName: "Dedi Supriyadi",
    shippingAddress: "Jl. Anggrek No. 5, Serang",
    courier: "AnterAja",
    trackingNumber: "ANTERAJA987654",
  },
];
