import { ReactNode } from "react";
import { CustomersType } from "../../../models/customers";
import { getWhatsAppLink } from "../../../utils/global";
import Modal from "../../ui/Modal";
import WhartsAppIcon from "../../icons/WhatsAppIcon";
import Barcode from "react-barcode";

interface ModalDetailCustomerProps {
  open: boolean;
  onClose: () => void;
  data: CustomersType | null;
}

const Field = ({
  label,
  value,
}: {
  label: string;
  value: string | ReactNode;
}) => {
  return (
    <div className="mb-3">
      <label className="fs-7 text-secondary fw-light">{label}</label>
      <p className="m-0">{value}</p>
    </div>
  );
};

const PROFILE = "https://i.pravatar.cc/280";

const ModalDetailCustomer = (props: ModalDetailCustomerProps) => {
  const { open, onClose, data } = props;

  return (
    <Modal open={open} title="Detail Customer" onClose={onClose}>
      <div className="row">
        <div className="col">
          <div className="row">
            <div className="col">
              <Field label="Nama" value={data?.name || ""} />
              <Field label="Alamat" value={data?.address || ""} />
            </div>
            <div className="col">
              <Field label="Email" value={data?.email || ""} />

              <Field
                label="No. Telepon"
                value={
                  <div className="mt-1">
                    <a
                      href={getWhatsAppLink(data?.phone || "")}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-decoration-none text-dark border px-3 py-1 rounded-2 d-flex align-items-center gap-2 w-fit"
                    >
                      <WhartsAppIcon className="text-success" />{" "}
                      <span>{data?.phone || ""}</span>
                    </a>
                  </div>
                }
              />
            </div>

            <Field
              label="Customer ID"
              value={
                <Barcode
                  value={`${data?.code}`}
                  height={24}
                  displayValue={false}
                />
              }
            />

            <div className="d-flex justify-content-start">
              <button className="btn btn-sm btn-outline-primary" type="button">
                Download
              </button>
            </div>
          </div>
        </div>
        <div className="col d-flex flex-column justify-content-start align-items-center">
          <picture>
            <source srcSet={PROFILE} type="image/svg+xml" />
            <img
              src={PROFILE}
              className="img-fluid img-thumbnail rounded-3 p-0"
              alt={data?.name}
            />
          </picture>

          <span className="fs-8 fw-light mt-1">
            Generated by: https://i.pravatar.cc/
          </span>
        </div>
      </div>
    </Modal>
  );
};

export default ModalDetailCustomer;
